### ISSUE TITLE
파싱부에서 malloc 실패했을 경우 예외처리

### ISSUE THREAD

**Issue by hanhee766** [grademe12/miniShell#5]
1) exit(1) 로 나가고 그냥 프로그램 종료
2) 할당된 친구들 전부 해제 후 새 프롬프트 띄우기 (명령어 실패했을때와 같이)

어떤 방향으로 구현하는게 좋을까요?
단순하게 생각하면 1이 편하긴 할텐데... 
사전에 할당된 친구들 해제하다가 여유 메모리가 생길수도 있다는 의견을 들으니까 그것도 말이 되는것같기도 해서요

**Comment by grademe12** [comment]
아 이거는 현준님의 의견을 존중하여 그냥 exit으로 나가는게 맞는것 같습니다. 램에 가용한 공간이 없으면 프로그램 종료시키고 os가 자원 회수하게 두는게 맞다고 봅니다 저도

**Comment by hanhee766** [comment]
그럼 1번으로 해석하고 프로그램 종료하는 방향으로 구현하겠습니다!
